# Default values for portainer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# If enterpriseEdition is enabled, then use the values below _instead_ of those in .image
enterpriseEdition: 
  enabled: false
  image:
    repository: portainer/portainer-ee
    tag: 2.0.2
    pullPolicy: Always

image:
  repository: portainer/portainer-ce
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

nodeSelector: {}

serviceAccount:
  annotations: {}
  name: portainer-sa-clusteradmin

service:
  # Set the httpNodePort and edgeNodePort only if the type is NodePort
  # For Ingress, set the type to be ClusterIP and set ingress.enabled to true
  # For Cloud Providers, set the type to be LoadBalancer
  type: NodePort
  httpPort: 9000
  httpNodePort: 30777
  edgePort: 8000
  edgeNodePort: 30776
  annotations: {}

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host:
      paths: []
  tls: []

resources: {}

persistence:
  size: "10Gi"
  annotations: {}
  storageClass:
