version: '3.3'
services:
  agent:
    image: portainer/agent:2.33.1
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
    volumes:
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine
      - type: bind
        source: C:\ProgramData\docker\volumes
        target: C:\ProgramData\docker\volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == windows]

networks:
  agent_network:
    driver: overlay
